[package]
name = "corrosive_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.3"
nalgebra = "0.32.2"
vulkano = "0.32.3"